
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!LICENSE'
      - '!README.md'
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: ./.github/setup-builder

      - name: Cargo format
        run: make check-fmt

      - name: Check diff
        run: git diff --exit-code

      - name: Cargo clippy
        run: make check-clippy

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Maximize build space (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          root-reserve-mb: 10240
          temp-reserve-mb: 10240

      - uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: ./.github/setup-builder

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: make build

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: ./.github/setup-builder

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: make test